require "user.map" -- Has to go first

require "user.copilot"
require "user.options"
require "user.keymaps"
require "user.alpha"
require "user.cmp" 
require "user.indent-blankline"
require "user.plugins"
require "user.project"
require "user.colorscheme"
require "user.lsp"
require "user.telescope"
require "user.nvimtree"
require "user.vim-test"
