require "user.options"
require "user.keymaps"
require "user.alpha"
-- require "user.cmp" TODO: uncomment if you want cmp
require "user.indent-blankline"
require "user.plugins"
require "user.project"
require "user.colorscheme"
require "user.lsp"
require "user.telescope"
require "user.nvimtree"
