# Change prefix from 'C-b' to 'C-Space'
unbind C-b
set-option -g prefix C-Space
bind-key Space send-prefix

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

# Load bashrc on new panes
set-option -g default-command "bash -l"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Set default split size for horizontal splits
set-hook -g after-split-window "resize-pane -y 30"

# Mouse on
set -g mouse on
set-option -s set-clipboard on

# Remove key delays
set -s escape-time 0

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

# Sane keymaps to create new sessions and navigate between them. Disabled if we
# are in Vim.
bind-key -n 'C-s' if-shell "$is_vim" '' 'new-session'
bind-key -n 'C-w' if-shell "$is_vim" '' 'choose-session'
bind-key -n 'C-n' if-shell "$is_vim" '' 'next-window'
bind-key -n 'C-p' if-shell "$is_vim" '' 'previous-window'

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# Resize panes with <leader>+shift+hjkl
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Sesh
bind-key "k" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# Recommended configurations for sesh
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
bind-key q kill-session # kill current session
bind-key S new-session # create a new session
bind -N "last-session (via sesh) " L run-shell "sesh last"
bind -N "switch to root session (via sesh) " 9 run-shell "sesh connect --root $(pwd)"
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# Keymaps for splitting panes
bind-key '\' split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"

# Position bar on top with no background and only the panes
set -g status-style bg=default
set -g status-right ""
set -g status-position top
